const router = require("express").Router();
const auth = require("../middleware/auth");
const requireTeacher = require("../middleware/requireTeacher");
const asyncHandler = require("../middleware/asyncHandler");
const c = require("../controllers/attendanceController");
router.get("/students", auth, asyncHandler(c.getStudents));
router.get("/summary", auth, asyncHandler(c.getMySummary));
router.get("/class-summary", auth, requireTeacher, asyncHandler(c.getClassSummary));
router.get("/", auth, asyncHandler(c.getAttendance));
router.post("/", auth, requireTeacher, asyncHandler(c.saveAttendance));
module.exports = router;
